# Generated by Django 4.1.3 on 2022-11-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscontent', '0003_alter_presscontent_label_alter_presscontent_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presscontent',
            old_name='url',
            new_name='slug',
        ),
    ]
